# Generated by Django 3.2.4 on 2021-06-16 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='Product',
            new_name='product',
        ),
    ]
