# Generated by Django 3.2.4 on 2021-06-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_rename_product_cartproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer'),
        ),
    ]
