# Generated by Django 3.2.4 on 2021-06-23 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0006_remove_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProudctImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eapp.product')),
            ],
        ),
    ]
